# Generated by Django 2.2 on 2019-05-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0002_habilidade_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='imagem',
            field=models.FileField(upload_to='fotossubidas/'),
        ),
    ]
