# Generated by Django 2.2 on 2019-05-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0004_auto_20190502_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='imagem',
            field=models.FileField(upload_to='affvei/'),
        ),
    ]
