# Generated by Django 2.2 on 2019-05-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0005_auto_20190502_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='imagem',
            field=models.FileField(upload_to='fotos/'),
        ),
    ]
