# Generated by Django 2.2 on 2019-05-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0006_auto_20190502_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='peso',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
