# Generated by Django 2.2 on 2019-05-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICACAO', '0007_pokemon_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='exp_base',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
